//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuntingSession
    {
        public string GameReserve { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> GameBirdAmt { get; set; }
        public Nullable<int> OtherBirdAmt { get; set; }
        public int Id { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
